services:
  disjfa_mozaic.mozaic_menu_listener:
    class: Disjfa\MozaicBundle\GlynnAdminMenu\MozaicMenuListener
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure' }

  disjfa_mozaic.unsplash_client:
    class: Disjfa\MozaicBundle\Services\UnsplashClient
    arguments:
      - '%disjfa_mozaic.unsplash_application_id%'
      - '%disjfa_mozaic.unsplash_secret%'
      - '@router'
      - '@doctrine.orm.entity_manager'

  disjfa_mozaic.unsplash_extension:
    class: Disjfa\MozaicBundle\Twig\UnsplashExtension
    public: false
    tags:
        - { name: twig.extension }
