<?php

namespace Disjfa\MozaicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnsplashUserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnsplashUserRepository extends EntityRepository
{

    /**
     * @param string $id
     * @return null|object
     */
    public function find($id)
    {
        return $this->findOneBy(['unsplashId' => $id]);
    }
}
