<?php

namespace Disjfa\MozaicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnsplashUserRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnsplashUserRepository extends EntityRepository
{
    /**
     * @param string $id
     * @param null   $lockMode
     * @param null   $lockVersion
     *
     * @return object|null
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return $this->findOneBy(['unsplashId' => $id]);
    }
}
