<?php

namespace Disjfa\MozaicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnsplashSeasonRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnsplashSeasonRepository extends EntityRepository
{
    public function findPublicSeasons()
    {
        return $this->createQueryBuilder('unsplashSeason')
            ->where('unsplashSeason.public = :public')
            ->setParameter('public', true)
            ->orderBy('unsplashSeason.dateSeason', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
